### ISSUE TITLE
Option to remove `Progressbar` when done

### ISSUE THREAD

**Issue by MarvinJWendt** [pterm/pterm#11]
Add an option to remove `Progressbar` when done.

**Comment by VictorAssunc** [comment]
I'm interested in this issue, but I need to ask a question: when you say "an option to remove Progressbar when done.", is it like a parameter for the progress bar to decide whether it will be removed or not or will it always be removed?

**Comment by MarvinJWendt** [comment]
Hi @VictorAssunc, the `Progressbar` has many options defined in this struct:

https://github.com/pterm/pterm/blob/26d9a656a156d464262b119f8359a3f06684ef7e/progressbar.go#L35-L56

You can make a new one which is called `RemoveWhenDone`
Then you can make a new function, which accepts a boolean as value.
Like here:
https://github.com/pterm/pterm/blob/26d9a656a156d464262b119f8359a3f06684ef7e/progressbar.go#L100-L104
You can implement the logic to remove the `Progressbar` here (just check that the option is set to true 😄): 
https://github.com/pterm/pterm/blob/26d9a656a156d464262b119f8359a3f06684ef7e/progressbar.go#L182-L185

**Comment by VictorAssunc** [comment]
Ok, i'll take it, thanks

**Comment by MarvinJWendt** [comment]
Are you working on it @VictorAssunc?

**Comment by VictorAssunc** [comment]
Yes, @MarvinJWendt, I started this week

**Comment by MarvinJWendt** [comment]
You can make a draft pull request when you have progress 🚀 
When you feel confident that your change works, you can mark it as `ready for review` and I will take a look at it! 😄
