### ISSUE TITLE
Rename every printer to have `Printer` as suffix

### ISSUE THREAD

**Issue by MarvinJWendt** [pterm/pterm#133]
This change makes PTerm more understandable and brings all printer names to the same style.
From now on, the convention is that every printer must end with 'Printer'.

- [x] Rename every printer
- [x] Rename very test
- [x] Rename every occurrence in comments
- [x] Check **every** example

@floaust please check those checkboxes before marking your pull request as ready.

**Comment by floaust** [comment]
checked. 😄
