### ISSUE TITLE
render bigtext error ?

### ISSUE THREAD

**Issue by rfyiamcool** [pterm/pterm#135]
code  from example

```
package main

import "github.com/pterm/pterm"

func main() {
	// Print a large text with the LetterStyle from the standard theme.
	// Useful for title screens.
	pterm.DefaultBigText.WithLetters(pterm.NewLettersFromString("PTerm")).Render()

	// Print a large text with differently colored letters.
	pterm.DefaultBigText.WithLetters(
		pterm.NewLettersFromStringWithStyle("P", pterm.NewStyle(pterm.FgCyan)),
		pterm.NewLettersFromStringWithStyle("Term", pterm.NewStyle(pterm.FgLightMagenta))).
		Render()
}
```

render

[![B6ToKU.png](https://s1.ax1x.com/2020/11/04/B6ToKU.png)](https://imgchr.com/i/B6ToKU)

**Comment by MarvinJWendt** [comment]
Hi @rfyiamcool, could you please tell me what terminal and which OS you are using? Have you changed your terminal font and/or theme? Thanks :)

**Comment by rfyiamcool** [comment]
os: mac
tool: iterm2
font: Monaco
theme: Dracula

**Comment by MarvinJWendt** [comment]
Thanks, I will take a look at it later this day :)

**Comment by MarvinJWendt** [comment]
Hi @rfyiamcool,
I just tried it on a mac. I can't replicate this bug.
I did set up my iTerm like you described. Maybe I accidentally solved your problem yesterday. Can you try version 'v0.12.2'?
Thank you 😄 

<img width="777" alt="Bildschirmfoto 2020-11-05 um 14 19 50" src="https://user-images.githubusercontent.com/31022056/98247466-f3633f80-1f73-11eb-8117-c08739bc492c.png">
<img width="711" alt="Bildschirmfoto 2020-11-05 um 14 22 15" src="https://user-images.githubusercontent.com/31022056/98247478-f52d0300-1f73-11eb-8b65-bbae1e8db333.png">
<img width="691" alt="Bildschirmfoto 2020-11-05 um 14 25 21" src="https://user-images.githubusercontent.com/31022056/98247495-f9f1b700-1f73-11eb-8056-36459c12fc0a.png">

**Comment by rfyiamcool** [comment]
thank you . 😁
