### ISSUE TITLE
Add spaces between operands by default

### ISSUE THREAD

**Issue by m5lk3n** [pterm/pterm#160]
Hi Marvin,

This is the FR as per our discussion (linked at the end).

One thing that I noticed is the following:

When I run 

```
package main

import (
	"fmt"
)

func main() {
	const name, age = "Kim", 22
	fmt.Println(name, "is", age, "years old.")
}
```

I get

`Kim is 22 years old.`

while

```
package main

import (
	"github.com/pterm/pterm"
)

func main() {
	const name, age = "Kim", 22
	pterm.Println(name, "is", age, "years old.")
}
```

produces

`Kimis22years old.`

The example is taken from Golang's documentation [here](https://golang.org/pkg/fmt/#Println) which states "_Spaces are always added between operands_".

Thanks!

_Originally posted by @m5lk3n in https://github.com/pterm/pterm/discussions/66#discussioncomment-269543_

**Comment by MarvinJWendt** [comment]
Hey, I just looked into this issue, and it's more complicated than I thought. 
`fmt.Println(...)` does not behave exactly like `fmt.Println(fmt.Sprint(...))`, like I expected. PTerm does use `fmt.Sprint` to format the string before printing.

**Comment by MarvinJWendt** [comment]
Fixed in `v0.12.9` 😄

**Comment by m5lk3n** [comment]
Thanks Marvin!

Just tried v0.12.9 with the following:

```
func main() {
	here := "here"
	pterm.FgLightWhite.Println("You are", here)
	pterm.Println("You are", here)
}
```
gives me
```
$ go run main.go 
You arehere
You are here
```

**Comment by MarvinJWendt** [comment]
Thanks again for pointing that out 😆 
I will fix it in the next hours :)

**Comment by m5lk3n** [comment]
Sorry, I hadn't realized that earlier.

**Comment by MarvinJWendt** [comment]
No problem ^^ I should have been more careful when looking into the issue :)

**Comment by MarvinJWendt** [comment]
I have updated every `TextPrinter` to the new way of handling `Sprintln` / `Println`.
The change is live in `v0.12.10`
Please let me know if you find anything else 👍

**Comment by m5lk3n** [comment]
Just tried `v0.12.11`, looks good - great, thanks a lot!
