### ISSUE TITLE
Renew website TLS certificate

### ISSUE THREAD

**Issue by MatthewEdwards** [pterm/pterm#164]
When I goto [Pterm](https://pterm.sh/) I get the following TLS error as the certificate has expired

![Screenshot 2021-02-13 at 01 04 46](https://user-images.githubusercontent.com/3919701/107837202-ca82ef80-6d97-11eb-99b0-42095e9f22e1.png)

**Comment by MarvinJWendt** [comment]
Hi @MatthewEdwards, thanks for the notice. I will fix this immediately!

**Comment by MarvinJWendt** [comment]
Certificate is renewed. Thanks again for the heads up! 😄 

To my future self: There was a bug which caused Nginx to use the old certificate. Have to investigate this further.
