### ISSUE TITLE
Printfln needs checkFatal

### ISSUE THREAD

**Issue by chaoedu** [pterm/pterm#196]
Printfln also needs checkFatal
pterm.Fatal.Printfln not panic

**Comment by MarvinJWendt** [comment]
Hi @chaoedu, I don't quite understand what you mean.
The `pterm.Fatal` printer always panics. `pterm.Error` doesn't.
If you want to force `pterm.Fatal` to **not** panic, you can use `pterm.Fatal.WithFatal(false).Printfln()`.

**Comment by chaoedu** [comment]
pterm.Fatal.Printfln() didn't panic as checkFatal not calling in this function.

**Comment by floaust** [comment]
Hey, @chaoedu you are right, I will fix it right away. :)

**Comment by MarvinJWendt** [comment]
Hi @chaoedu, thanks for the bug report! The issue is fixed and released under [`v0.12.17`](https://github.com/pterm/pterm/releases/tag/v0.12.17).
