### ISSUE TITLE
User input preety field with validation

### ISSUE THREAD

**Issue by xbipin** [pterm/pterm#213]
since we currently have most of the UI elements it would be nice to have a user input box with validation and default value

**Comment by MarvinJWendt** [comment]
Hi @xbipin, thanks for the suggestion. We've been thinking about interactive components (like input, confirm, dropdown, etc.) for a long time now, but we aren't sure if it really fits into PTerm at the moment, as we would have to create a whole new category of printers, "InteractivePrinter", or something like that.

**Comment by leighmcculloch** [comment]
This is something I'm trying to figure out as well. If it doesn't fit into PTerm, which I think might make sense, what do others typically pair with PTerm?

**Comment by MarvinJWendt** [comment]
Hi @leighmcculloch, for the time that we do not have our own `InteraxctivePrinters`, I would recommend something like https://github.com/AlecAivazis/survey :)

**Comment by MarvinJWendt** [comment]
`InteractivePrinters` are a thing now, closing this :)
