### ISSUE TITLE
can run multi Spinner in at the same time

### ISSUE THREAD

**Issue by goodking-bq** [pterm/pterm#215]
like this:
```go
// Create and start a fork of the default spinner.
	spinnerSuccess, _ := pterm.DefaultSpinner.Start("Doing something important... (will succeed)\n")
	go func() {
		time.Sleep(time.Second * 2) // Simulate 3 seconds of processing something.
		spinnerSuccess.Success()    // Resolve spinner with success message.
	}()

	// Create and start a fork of the default spinner.
	spinnerWarning, _ := pterm.DefaultSpinner.Start("Doing something important... (will warn)\n")
	go func() {
		time.Sleep(time.Second * 2) // Simulate 3 seconds of processing something.
		spinnerWarning.Warning()    // Resolve spinner with warning message.
	}()
```

**Comment by MarvinJWendt** [comment]
Thanks for the suggestion, we will work on this :)

**Comment by markusressel** [comment]
Hey there, awesome lib I like it a lot!
I would also like to use multiple progressbars concurrently, is this within the scope of this issue?

**Comment by floaust** [comment]
We will work on this ASAP 👍

**Comment by TanZng** [comment]
this would be really cool feature!

**Comment by MarvinJWendt** [comment]
Sadly not yet, we're working on interactive printers in the background at the moment :)

**Comment by wernerdweight** [comment]
Any ETA on this? Thanks

**Comment by MarvinJWendt** [comment]
Yes, this taking long indeed, sorry for that. Currently, it looks like we would need to rewrite a huge part of every live printer to enable multiple live printers at a time. We're still trying to figure out how to do this without introducing a breaking change.

Another option would be to introduce a `MultiSpinner` or something like that. But that would make it very verbose, if we need to introduce that for every live printer. 

We also want to make live printers combinable, this would make multiple spinners possible, but we would have to rewrite the internals completely. This will definitely be the next big thing for PTerm.

**Comment by liblaf** [comment]
Any progress 👀

**Comment by MarvinJWendt** [comment]
This is currently blocked by #447.

**Comment by MarvinJWendt** [comment]
Hey, I know it took a long time, but we finally did it:

https://github.com/pterm/pterm/assets/31022056/2ebd4d19-072f-441f-bd0d-6d2694013f9f

Tracking in #544 now 🚀

**Comment by mort666** [comment]
looking really good @MarvinJWendt, however any idea when the changes will get merged and potentially released?

**Comment by MarvinJWendt** [comment]
Hi @mort666, most likely this weekend :)

**Comment by mort666** [comment]
Awesome.. Perfect timing as I'm working on something this weekend that is going to make good use of this...

**Comment by MarvinJWendt** [comment]
The PR was just merged. I am creating a release in the next minutes.

You can take a look at https://github.com/pterm/pterm/tree/master/_examples/multiple-live-printers to see example usages.
The examples for `Spinner` and `Progressbar` have also been updated with examples for multiple printers at the same time.
