### ISSUE TITLE
Add Frame around Table

### ISSUE THREAD

**Issue by dfreilich** [pterm/pterm#225]
As a user, I would like to print a border around my Table. I'm assuming I can do that with a Box at the moment, through some hackery, but it's not immediately obvious how to do that, and a setting on `Table` would make it much more convenient.

**Comment by MarvinJWendt** [comment]
Hi @dfreilich, we can add this as an option :)

For now, you can use this:

```go
table, _ := pterm.DefaultTable.WithData(pterm.TableData{
  {"Name", "Age"},
  {"Marvin", "20"},
  {"Bob", "19"},
  {"Alice", "21"},
}).WithHasHeader().Srender()

pterm.DefaultBox.Println(table)
```

Which results in: 
![image](https://user-images.githubusercontent.com/31022056/124112727-df240380-da6a-11eb-84a1-ccecfbf9135d.png)

**Comment by MarvinJWendt** [comment]
Hi @dfreilich, the PR is merged. I will wait for all tests to pass, and then I'll make a new release. Should be ready in about 10 minutes.

You can then use:

```go
	pterm.DefaultTable.WithData(pterm.TableData{
		{"Name", "Age"},
		{"Marvin", "20"},
		{"Bob", "19"},
		{"Alice", "21"},
	}).WithHasHeader().WithBoxed().Render()
```

**Comment by dfreilich** [comment]
That was wildly fast, @MarvinJWendt. As a fellow OSS maintainer (albeit on a smaller scale), I'm amazed. Thanks so much!

**Comment by MarvinJWendt** [comment]
Thanks for the compliment 😄
