### ISSUE TITLE
a function to print using a ANSI standard writer 

### ISSUE THREAD

**Issue by Lirb** [pterm/pterm#231]
Hello, 
I'm trying to use tview module for get data and pterm to print results, but I wasn't been able to print any liveprinter type on terminal, using tview's AnsiWriter method, that returns a io.writer, and setted it as pterm's default output.

Attach a capture about how it looks a progressBar using tview's AnsiWriter. 
![image](https://user-images.githubusercontent.com/18729663/125542508-1bdc7442-f75d-4457-85a7-f6ed98e53b0a.png)

**Comment by MarvinJWendt** [comment]
PTerm was not designed to work with other libraries together. Altough, we have `InteractivePrinters` now, which could be combined with normal ones.
