### ISSUE TITLE
Style italic

### ISSUE THREAD

**Issue by informeai** [pterm/pterm#237]
Is there any option where the terminal output is italic style?

**Comment by MarvinJWendt** [comment]
Yes!

```go
// Pure italic
pterm.Italic.Println("Hello, World!")

// Italic with color (custom style)
pterm.NewStyle(pterm.Italic, pterm.FgRed).Println("Hello, World")
```

![image](https://user-images.githubusercontent.com/31022056/126147003-a24fa8c5-6008-473e-a327-e447dada6841.png)

**Comment by informeai** [comment]
> Yes!
> 
> ```go
> // Pure italic
> pterm.Italic.Println("Hello, World!")
> 
> // Italic with color (custom style)
> pterm.NewStyle(pterm.Italic, pterm.FgRed).Println("Hello, World")
> ```
> 
> ![image](https://user-images.githubusercontent.com/31022056/126147003-a24fa8c5-6008-473e-a327-e447dada6841.png)

I'm sorry...
thanks

**Comment by MarvinJWendt** [comment]
No problem 😄
