### ISSUE TITLE
PrefixPrinter: Expose call stack number

### ISSUE THREAD

**Issue by ccremer** [pterm/pterm#256]
Hi!
Great project!
As part of another CLI project I am working on I have created [plogr](https://github.com/ccremer/plogr), which is a pterm implementation for the [logr](https://github.com/go-logr/logr) logging API.

I like how the `ShowLineNumber` in the PrefixPrinter shows the file and line where e.g. `Println` has been called. However, when this `Println` call is nested, then it shows the wrong file number due to `3` being hardcoded here:

https://github.com/pterm/pterm/blob/bbbae943b9e6640563f75e50b9878591e4a498bb/prefix_printer.go#L185

In the mentioned plogr project, this always is something like

```go
	sink := plogr.NewPtermSink()
	sink.ErrorPrinter = *pterm.Error.WithShowLineNumber(true)
	logger := logr.New(sink)
	logger.WithName("manager").Error(errors.New("an error"), "Error message")
```

```console
  ERROR    (manager) Error message (error="an error")
└ (/home/chris/Documents/source/ccremer/plogr/sink.go:87)
```
Displaying the source file and line number of the logr implementation isn't helpful. 

Idea: Add an offset to the PrefixPrinter (e.g. `ShowLineNumberOffset`, name debatable) with default being `0`. It gets added to the hardcoded `3` without breaking changes. So the internal usage is something like

```go
	_, fileName, line, _ := runtime.Caller(3+p.ShowLineNumberOffset)
```
That way, when configuring the prefix printers, one can give an offset of e.g. `3`, totalling to 6, which in my case would be the actual call to `Error`.

**Comment by MarvinJWendt** [comment]
Hi @ccremer, that's a good idea! We'll work on this soon :)

**Comment by ccremer** [comment]
Thanks for integrating it!
I will try it out soon
