### ISSUE TITLE
Add a `AreaPrinter.Clear()` function

### ISSUE THREAD

**Issue by floaust** [pterm/pterm#264]
Add a `AreaPrinter.Clear()` function.

This should be a wrapper for `p.area.Clear()`.

**Comment by GibranHL0** [comment]
Hi 👋

I'd like to be assigned to this issue and give it a try.

**Comment by floaust** [comment]
Have fun :)

**Comment by mohammadjalali** [comment]
Hi, are you still working on this?
I would like to work on this too. Please let me know if I can.

**Comment by MarvinJWendt** [comment]
Done in #265
