### ISSUE TITLE
Tests flaky on linux/macos

### ISSUE THREAD

**Issue by TobiaszCudnik** [pterm/pterm#289]
While working on #246 Ive discovered that I cant reliably run tests on neither linux nor macos (random tests are failing).

Example:
```
%s
--- FAIL: TestBasicTextPrinterPrintMethods (0.02s)
    --- FAIL: TestBasicTextPrinterPrintMethods/Print (0.00s)
        --- FAIL: TestBasicTextPrinterPrintMethods/Print/1.5#01 (0.00s)
            utils_test.go:31: 
                
                   1| An object does not contain the object it should contain.
                   2| 
                   3| object:
                   4| (string) ""
                   5| 
                   6| element that is missing in object:
                   7| (string) (len=3) "1.5"
                
                
FAIL
exit status 1
FAIL	github.com/pterm/pterm	0.587s
```

The problems seems to be `captureStdout`, which sometimes does not capture. Ive also noticed that the CI is on windows?

I had some luck with adding a timeout or printing a random character after every capture, but nothing really stable (yet way more stable then the current situation).

Any help appreciated, as initial bits for #246 are working (so are the missing parts for them in `textza`).

Maybe Im missing something obvious? Steps:
1. `git clone`
2. `go mod tidy`
3. `go test`

**Comment by MarvinJWendt** [comment]
Hi @TobiaszCudnik, yes, you're right. The test don't work properly on Linux machines.  Somehow, Linux machines cannot handle the mass of `captureStdout` calls. I looked that up before, but that's long ago. It had something to do with a hard coded limit in Linux, if I remember correctly. Windows does handle terminal output a little different, so it does not have that limitation. It might be that we can fix this with `testza`, but I didn't find a good solution, yet. I can give it a try again and I will let you know if I find something :)

**Comment by MarvinJWendt** [comment]
I found the error again:

> Linux systems limit the number of file descriptors that any one process may open to 1024 per process. (This condition is not a problem on Solaris machines, x86, x64, or SPARC). After the directory server has exceeded the file descriptor limit of 1024 per process, any new process and worker threads will be blocked.

That's exactly what's happening here. If we include error handling  in the `captureStdout` function, these are the errors:

```
read |0: bad file descriptor
close |0: bad file descriptor
```

**Comment by TobiaszCudnik** [comment]
Thanks @MarvinJWendt, but I doubt its related to the file descriptor limit (its not watching any files) and Ive done some simple tests with a counter, which:
- pass after the first failure
- the number doesnt match the limit

Ive also increased the limit with `ulimit -n 9400` which changed nothing.

Id suggest writing to a buffer instead of stdout for unit tests and write a smaller amount of acceptance tests which assert stdout.

For now the workaround I found is to run tests file-by-file eg
`go test -v -run TestPrefixPrinter`

**Comment by MarvinJWendt** [comment]
Yeah, writing to a buffer could be a good alternative.
If you want, you can create a draft PR. In that case I could look at your changes from time to time and we would have a place to discuss the implementation, if there are any questions on your side 😄
