### ISSUE TITLE
New icon for PTerm

### ISSUE THREAD

**Issue by MarvinJWendt** [pterm/pterm#30]
Make new icon before `v1.0.0` is released. Icon will be used by the organization profile and in the `README.md`.

Icon must be released under [CC0](https://creativecommons.org/publicdomain/zero/1.0/) or similar.

**Comment by nshem** [comment]
Hi. i can make an icon. can you assign me?
I'll soon send some options so you can choose or guide further. @MarvinJWendt 
thanks
