### ISSUE TITLE
Progress bar doesnt print if the last message is not a success

### ISSUE THREAD

**Issue by Vano2903** [pterm/pterm#302]
I was trying to print a few logs but the last one was a warning, after the warning the function finished but the progress bar didn't print.

	func installingPseudoList() {
        var pseudoProgramList = strings.Split("pseudo-excel pseudo-photoshop pseudo-chrome pseudo-outlook pseudo-explorer "+
		"pseudo-dops pseudo-git pseudo-vsc pseudo-intellij pseudo-asd pseudo-scoop pseudo-minecraft", " ")
		pterm.DefaultSection.Println("Installing pseudo programs")

		p, _ := pterm.DefaultProgressbar.WithTotal(len(pseudoProgramList)).WithTitle("Installing stuff").Start()
		for i := 0; i < p.Total; i++ {
			p.UpdateTitle("Installing " + pseudoProgramList[i])
			if pseudoProgramList[i] == "pseudo-minecraft" {
				pterm.Warning.Println("Could not install pseudo-minecraft\nThe company policy forbids games.")
			} else {
				pterm.Success.Println("Installing " + pseudoProgramList[i])
				p.Increment()
			}
			time.Sleep(time.Second / 2)
		}
		p.Stop()
	}

If you run this function, since Minecraft is the last, the last log will be a warning which will lead to the progress bar not to print

**Comment by MarvinJWendt** [comment]
Hi, thanks for the report! I'll take a look at this soon :)

**Comment by MarvinJWendt** [comment]
Hi @Vano2903, fixed! This will be in the release today :)
Thanks for reporting!
