### ISSUE TITLE
GetConsoleScreenBufferInfo is not worked in vscode "debug console"

### ISSUE THREAD

**Issue by maseer** [pterm/pterm#306]
GetConsoleScreenBufferInfo is not worked in vscode "debug console".

**Comment by MarvinJWendt** [comment]
Can you provide some more details please?

**Comment by maseer** [comment]
`GO111MODULE=on
GOARCH=amd64
GOOS=windows
GOVERSION=go1.18beta1
GCCGO=gccgo
GOAMD64=v1
AR=ar
CC=gcc
CXX=g++
CGO_ENABLED=1`

vscode config:
`
    "configurations": [
        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceFolder}",
        }
    ]
`

I code golang with vscode, got a issue:

In terminal,it works well:
![5094C898-682C-4369-AE55-29BCA45ED1F6](https://user-images.githubusercontent.com/9444724/149690637-1a3d7577-e6c5-4102-b9c6-6a617baa90d2.png)

In debug console:
![Dingtalk_20220117102002](https://user-images.githubusercontent.com/9444724/149691315-4b049de4-4fee-456b-ba10-024053074823.jpg)

So I found out the function "GetConsoleScreenBufferInfo" didn't work well in vscode "debug console".

This issue looks like should be resolved by vscode more than pterm.

**Comment by MarvinJWendt** [comment]
Yes, sadly we cannot detect if the application is running inside the VS Code debug terminal. I can't tell you why this is happening, sorry.

**Comment by MarvinJWendt** [comment]
I don't think we can fix this, as VSC somehow messes with the terminal output in the debug window. It should probably be reported to them.
