### ISSUE TITLE
Option to disable all output

### ISSUE THREAD

**Issue by MarvinJWendt** [pterm/pterm#31]
Option to disable all output.

```go
pterm.DisableOutput = true
```

🔝 this should disable all Print functions, so that PTerm does not print anything.
Can be used to run CLI tools in `quiet` or `silent` mode.

**Comment by m1ome** [comment]
Can you please describe more what do you mean saying "disable all output"? 
I mean literally, short example will be helpful

**Comment by MarvinJWendt** [comment]
Updated the description @m1ome :)

**Comment by m1ome** [comment]
👍

**Comment by m1ome** [comment]
@MarvinJWendt submitted PR to solve this one
