### ISSUE TITLE
Show progress of `Progressbar` in the middle of the progressbar

### ISSUE THREAD

**Issue by MarvinJWendt** [pterm/pterm#33]
Show progress of `Progressbar` in the middle of the progressbar.

**Comment by m1ome** [comment]
Does it should be configurable or by default?

**Comment by MarvinJWendt** [comment]
By default would fit for now :)
Configurable would be even better, tho 😄 
@m1ome

**Comment by m1ome** [comment]
ty for answer will look at it now

**Comment by MarvinJWendt** [comment]
We decided that the current style of the `Progressbar` might look better.
