### ISSUE TITLE
Rendering issues in Windows Cmd and PowerShell

### ISSUE THREAD

**Issue by carlosm27** [pterm/pterm#345]
Hi, How are you? I have been trying Pterm for the first time and I have been getting rendering issues in PowerShell:
![image](https://user-images.githubusercontent.com/70811425/164310975-f270b5c2-00e2-4894-825b-920b97f703e6.png)

And Windows CMD:
![image](https://user-images.githubusercontent.com/70811425/164311054-2e41e722-bfd8-4a38-a2bb-bb841d276d07.png)
 I'm using Windows 7, and Go 1.16

The features I'm trying to use are Tables and the one in the QuickStart.
Have a nice day.

**Comment by MarvinJWendt** [comment]
Hi @carlosm27, I am good, thanks for asking! 
This is, indeed, very weird behavior.

Could you please run this snippet, and reply with a screenshot?

```go
package main

import (
	"fmt"

	"github.com/pterm/pterm"
)

var counter int

func main() {
	section(func() {
		pterm.FgRed.Println("Should be red")
	})

	section(func() {
		fmt.Println("\u001b[31mShould be red\u001b[0m")
	})

	section(func() {
		fmt.Println("No color")
	})

	section(func() {
		pterm.Println("\u001b[31mShould be red\u001b[0m")
	})

	section(func() {
		pterm.NewStyle(pterm.FgRed).Println("\u001b[31mShould be red\u001b[0m")
	})
}

func section(content func()) {
	counter++
	fmt.Printf("Test (%d)\n", counter)
	content()
	fmt.Println()
}
```

**Comment by carlosm27** [comment]
![image](https://user-images.githubusercontent.com/70811425/164322888-67abb8b1-869a-4dd6-a35c-0769934a9589.png)

**Comment by MarvinJWendt** [comment]
Hi @carlosm27, I did some research and as it seems, Windows CMD (before Win10) does not support colors using ANSI codes (as you can see in `Test (2)`). 

But, you can use PTerm without color too! Just call `pterm.DisableColor()` at the start of your app.

**Comment by carlosm27** [comment]
Oh good. What about tables and other features of Pterm? Thank you.

**Comment by carlosm27** [comment]
Sorry for asking that before trying it. But, yes it works.
 
![image](https://user-images.githubusercontent.com/70811425/164327857-6205a1d1-a3a9-4b8e-958c-76517ace32a7.png)

Thank you. Have a nice day.

**Comment by MarvinJWendt** [comment]
You're welcome, let me know if you need help with anything!
