### ISSUE TITLE
`InteractiveMultiselect` keys

### ISSUE THREAD

**Issue by luisdavim** [pterm/pterm#385]
I think that using `space` to toggle a selection and `enter` to confirm would be more intuitive than the current keys, `enter` to select and `tab` to confirm.
Maybe we could store the keys in a map and allow the users to customize them? What do you think?

**Comment by MarvinJWendt** [comment]
Yes, that was actually the way we intended to do it, but we figured out that we need the space bar for actual spaces in the fuzzy search.

Giving the option to customize the keys could be done, but that would most likely mess with the fuzzy search function and people would probably not think about the "consequences". For example, if someone sets "a" to select all, and "d" to deselect all, his users would randomly select and deselect items when searching for words that contain an "a" or "d".

**Comment by luisdavim** [comment]
yeah, that makes sense.
