### ISSUE TITLE
User input reappears with ``InteractiveTextInput``

### ISSUE THREAD

**Issue by loutrerusse** [pterm/pterm#387]
Hi, first of all, thank you for this incredible project.
On Windows 11, Go 1.19:
```go
f, _ := pterm.DefaultInteractiveTextInput.Show("First Input")
s, _ := pterm.DefaultInteractiveTextInput.WithMultiLine(true).Show("Second Input")
```
will output as:
```
First Input: <my input>
Second Input: <my first input>
```
so the first input will pop up when i call the second input, i can still use backspace to remove the input but it's a bit embarrassing.

**Comment by MarvinJWendt** [comment]
Hi @loutrerusse, thanks for the report! I am currently on vacation, I will look into it ASAP!

**Comment by wvkranenburg** [comment]
Same here on OSX, thanks for looking in to it!
