### ISSUE TITLE
Multi spinner and logs

### ISSUE THREAD

**Issue by psihachina** [pterm/pterm#390]
Hi, 

We use your library in our project and we really like it. But some things we have to replace, such as multi spinner and logs in spinner. Here is an example with logs in the spinner: 
[![asciicast](https://asciinema.org/a/4GV9kffoqqW4pmv9tyH8FlDy0.svg)](https://asciinema.org/a/4GV9kffoqqW4pmv9tyH8FlDy0)

Are these features possible? Or maybe I can help implement them?

**Comment by MarvinJWendt** [comment]
Hi @psihachina, `MultiSpinners` are a planned feature :)
I can't tell you when we're going to implement this, as we are very bussy currently, sorry for that! I will keep this issue open and notify you, when we know more 😄

**Comment by psihachina** [comment]
Hi, @MarvinJWendt 

What do you think about the operation logs that are displayed under the spinner? In the example I showed

**Comment by MarvinJWendt** [comment]
Hi @psihachina, sorry I somehow missed to reply.

You can simply use any print function of pterm, such as `pterm.Println()`, while a spinner is running. The prints will then be above the spinner. This is somehow like a log and can be used with `pterm.Info.Println()` etc. to signal the status of steps.

**Comment by MarvinJWendt** [comment]
Multi spinner is coming with #544
