### ISSUE TITLE
Disable macOS CI tests

### ISSUE THREAD

**Issue by MarvinJWendt** [pterm/pterm#410]
macOS should no longer be tested in CI. We have so many tests that capture the console output, that macOS runs out of file descriptors and fails. This is done by removing macOS from the matrix set in the workflow (GitHub Actions) file.

**Comment by rafaelrubbioli** [comment]
Hey @MarvinJWendt ! Can i work on this one?

**Comment by MarvinJWendt** [comment]
Yeah sure :)
