### ISSUE TITLE
Add an option to change checkmarks in the interactive multiselect

### ISSUE THREAD

**Issue by xMajkel** [pterm/pterm#418]
I've run into an issue where Windows console isn't able to render the default multiselect's checkmarks ("✓" and "✗") due to them being undefined in the standard "Consolas" font.  I don't really feel like changing a font nor manually changing anything in the PTerm's source code. An option to define them would be a great addition to this awesome project.

**Comment by MarvinJWendt** [comment]
Sure, will do!

**Comment by KarolosLykos** [comment]
Hi guys, I thought I could help here so I created a pr with the requested change. I decided to add an option to define Selected/NotSelected checkmarks as a struct. I kept the default checkmarks ("✓" and "✗") for the default printer. 

@MarvinJWendt I also added an example based on the `interactive_multiselect/custom-keys`.
