### ISSUE TITLE
I event cannot run demo as show

### ISSUE THREAD

**Issue by SilverChard** [pterm/pterm#428]
when 15:30:46 run demo area like this
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/9633121/209775414-d2fd14f1-ef7d-4deb-802e-5380dd10b1c7.png">

run box demo like this
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/9633121/209775610-776fd55a-a5fa-4c57-9610-610d130eea8a.png">

Font: SF Mono Regular  
FontSize: 13

github.com/pterm/pterm@v0.12.51

**Comment by MarvinJWendt** [comment]
Hi @SilverChard, I cannot reproduce the problem. Have you found a solution? My best guess would be that this is the terminals fault. Which one are you using? Have you resized the terminal window, while the demo was running?

**Comment by SilverChard** [comment]
then running, I have not resize terminal window.
And I can reproduce this problem under mac os 12 native terminal and iTerm2(Build 3.4.18).

<img width="1636" alt="image" src="https://user-images.githubusercontent.com/9633121/215323254-263545c9-381c-4a41-a3d6-88ed2365653a.png">

I realized that this problems may be because these demos all use Box??

Panel2 is not aligned based on panel1, but treats itself as the first panel. but title can align base on panel1.

In fact, I put some result in pterm's panel render by other terminal table's lib , it works perfect.

**Comment by akihiro17** [comment]
I encountered a similar issue. I believe this problem arises due to the width of box-drawing characters like '└' being 2 in certain environments.

Ref: https://github.com/mattn/go-runewidth/issues/14

In my environment, setting RUNEWIDTH_EASTASIAN to 0 resolves the issue.

```golang
package main

import "github.com/pterm/pterm"

func main() {
	pterm.Info.Println("This might not be rendered correctly on GitHub,\nbut it will work in a real terminal.\nThis is because GitHub does not use a monospaced font by default for SVGs")

	panel1 := pterm.DefaultBox.Sprint("Lorem ipsum dolor sit amet,\nconsectetur adipiscing elit,\nsed do eiusmod tempor incididunt\nut labore et dolore\nmagna aliqua.")
	panel2 := pterm.DefaultBox.WithTitle("title").Sprint("Ut enim ad minim veniam,\nquis nostrud exercitation\nullamco laboris\nnisi ut aliquip\nex ea commodo\nconsequat.")
	panel3 := pterm.DefaultBox.WithTitle("bottom center title").WithTitleBottomCenter().Sprint("Duis aute irure\ndolor in reprehenderit\nin voluptate velit esse cillum\ndolore eu fugiat\nnulla pariatur.")

	panels, _ := pterm.DefaultPanel.WithPanels(pterm.Panels{
		{{Data: panel1}, {Data: panel2}},
		{{Data: panel3}},
	}).Srender()

	pterm.DefaultBox.WithTitle("Lorem Ipsum").WithTitleBottomRight().WithRightPadding(0).WithBottomPadding(0).Println(panels)
}

```

```sh
go run main.go
```
![image](https://github.com/pterm/pterm/assets/7583548/05ce8bb5-4b70-4a98-b7c4-c8d5af3837e4)


```sh
RUNEWIDTH_EASTASIAN=0 go run main.go
```

![image](https://github.com/pterm/pterm/assets/7583548/29bae7d7-1df8-4cbb-9bd7-5e75eea7af10)

**Comment by MarvinJWendt** [comment]
As @akihiro17 mentioned, this is a problem with east asian environments. We'll track the progress in #255
