### ISSUE TITLE
Add `ListPrinter`

### ISSUE THREAD

**Issue by MarvinJWendt** [pterm/pterm#43]
`ListPrinter` should implement `TextPrinter`. Should be able to print leveled lists.

### Example:

```
- Level one
  - Level two
- This is an example
  - level 2
    - level 3
```

**should print:**

- Level one
  - Level two
- This is an example
  - level 2
    - level 3

**Comment by floaust** [comment]
pls asign me 😄 🙏

**Comment by moogacs** [comment]
@floaust if you didn't start on it , I can start work on it if you don't mind

**Comment by floaust** [comment]
@moogacs it's already almost done, just need to be tested. Had much to do the last days
