### ISSUE TITLE
Add `TextPrinter` variant which prints normal text

### ISSUE THREAD

**Issue by MarvinJWendt** [pterm/pterm#45]
Add `TextPrinter` variant which prints normal text - this can be used to resolve progressbars and spinners for example.

**Comment by suramrit** [comment]
Hi @MarvinJWendt Was thinking about taking this up for my hacktoberfest submission. Can you explain what you mean by *`"this can be used to resolve progressbars and spinners for example"`*

**Comment by MarvinJWendt** [comment]
Hi @suramrit, we have a struct called `Progressbar`. Another one is `Spinner`, which shows that a process with unknown length is running. When a `Spinner` ends, it can be replaced with any type of `TextPrinter`, as you can see here: https://github.com/pterm/pterm/tree/master/_examples/spinner
At the moment the spinners are mostly replaced with `PrefixPrinters` (success, warning, etc...).
The feature, that we want to implement with this issue, is to have a basic printer (implementing `TextPrinter`), which prints the input as-is. So that a `Spinner` for example, can be resolved with basic text.
You can find a template for a new `TextPrinter` here: https://github.com/pterm/pterm/blob/master/CONTRIBUTING.md
I hope this is more detailed now :)

**Comment by suramrit** [comment]
Thanks for the explanation! I would be happy to take this up and finish it to the best of my ability 😄  
If you want, you can assign this to me.

**Comment by MarvinJWendt** [comment]
Here you go 😉 
You can make a new file called `basic_text_printer.go` and the struct can be called `BasicTextPrinter` 🚀

**Comment by MarvinJWendt** [comment]
Are you working on this @suramrit?

**Comment by suramrit** [comment]
@MarvinJWendt Yes. Sorry Ive been a bit slow.
