### ISSUE TITLE
Better error handling in CI System

### ISSUE THREAD

**Issue by MarvinJWendt** [pterm/pterm#47]
The `CI` System is located here: https://github.com/pterm/pterm/blob/master/ci/main.go
This program is executed on each push and updates the animations of the individual components. Since a goroutine is started for each component, it is a bit tricky to arrange the console output.

The goal of this ticket is to output errors that happen during the generation and make the action fail.

**Comment by FabianBG** [comment]
Hi, I can help with that. So basically you want to log the execution of external commands errors of the go routines and maybe panic if some of them fails or do all the tasks and print an error report ??

**Comment by MarvinJWendt** [comment]
> do all the tasks and print an error report

Exactly that! 😄 

Ping me when you want to be assigned :)

**Comment by FabianBG** [comment]
Awesome can you pls assign it to me to start working on it and can you pls add the label hacktoberfest-accepted to the issue

**Comment by MarvinJWendt** [comment]
Hi @FabianBG. The `hacktoberfest-accepted` label is not needed for Hacktoberfest :) When your PR is merged it'll automatically be accepted! 🚀 

> Your PR has not yet been accepted by a maintainer. **A maintainer can accept your PR by merging it**, adding the "hacktoberfest-accepted" label to it, or approving it.

**Comment by FabianBG** [comment]
Created the pr can you check it pls :D https://github.com/pterm/pterm/pull/61
