### ISSUE TITLE
Add theme support

### ISSUE THREAD

**Issue by MarvinJWendt** [pterm/pterm#48]
Add theme support to PTerm.

- Theme should be a struct. 
- A default theme should be used for default printers. 
- Each printer should have a theme option.

### Theme Support

- [x] `PrefixPrinter`
- [x] `HeaderPrinter`
- [x] `Progressbar`
- [x] `Spinner`
- [x] `Table`
- [x] `Section`

Current progress in https://github.com/pterm/pterm/tree/feat/theme-support

**Comment by A-Annan** [comment]
can I work on it?

**Comment by MarvinJWendt** [comment]
Yeah, sure :)

**Comment by MarvinJWendt** [comment]
Are you working on this @A-Annan?

**Comment by A-Annan** [comment]
> Are you working on this @A-Annan?
I planned to start today!

**Comment by MarvinJWendt** [comment]
Hey @A-Annan, it's actually a little more complicated than I thought. I made a branch for this issue with current progress. If you want you can fork that and direct your pull-request into it :)

**Comment by A-Annan** [comment]
ok I will thank you
