### ISSUE TITLE
Progress bar has no width (does not display bar filler) until first increment

### ISSUE THREAD

**Issue by emma-alexandria** [pterm/pterm#495]
I've been having a slight issue with the progress bar. My basic setup looks like this: 

```golang
termWidth, _ := util.TermSize(int(os.Stdout.Fd()))

	maxWidth := int(float32(termWidth) * 0.75)

	barStyle := pterm.NewStyle(pterm.FgRed)
	titleStyle := pterm.NewStyle(pterm.FgWhite)

	progressbar, _ := pterm.DefaultProgressbar.
		WithTotal(len(files)).
		WithShowElapsedTime(true).
		WithElapsedTimeRoundingFactor(time.Second).
		WithBarFiller("░").
		WithMaxWidth(maxWidth).
		WithBarStyle(barStyle).
		WithTitleStyle(titleStyle).
		WithShowPercentage(false).
		Start("Looping through files")
```

In code, the progressbar gets incremented in a pretty simple way. A list of files is looped through, and under a few conditions a quick operation will be done, and under other conditions a long multi second operation will be done, with an increment after each.

The problem comes when the first operation is a long one, which leads to the progress bar displaying like this for a few seconds:
![image](https://user-images.githubusercontent.com/68666531/235441348-6226f17f-87b4-4158-8dce-be4e424fda1c.png)

Until it gets incremented when it suddenly pops into full width:
![image](https://user-images.githubusercontent.com/68666531/235441438-b267d085-05f5-46f3-a7f6-78afff932910.png)

I'm assuming the intended behaviour is for the progress bar to display the barfiller even when 0 increments have occurred.

**Comment by MarvinJWendt** [comment]
Hi @emma-alexandria, this is now fixed in #499 by @KarolosLykos. 
I will release it in the next hours. Thanks for reporting the issue!
