### ISSUE TITLE
wrong print of box with title including asian characters 

### ISSUE THREAD

**Issue by FLAGLORD** [pterm/pterm#526]
If the title of box includes asian characters, it would not print in a pretty way.
```text
┌─ 测试 ─┐
|          |
└──────────┘

```
https://github.com/pterm/pterm/blob/20d3f63d8d77038cca3bbddbee141e444c093590/box_printer.go#L243
 `Len()` is not suitable for asian characters. Maybe `runewidth.StringWidth()` is a better choice.

**Comment by MarvinJWendt** [comment]
Thanks for reporting the issue! Will be fixed in the next release.
