### ISSUE TITLE
Update Contributing guidelines

### ISSUE THREAD

**Issue by MarvinJWendt** [pterm/pterm#54]
Update `CONTRIBUTING.md` file.

**Comment by umutphp** [comment]
Hi @MarvinJWendt ,

Many thanks for this great module :+1: .

The contributing document seems ok for me :). Maybe, a simple ToC can be added at the top of document. Why do you think It needs to be updated?

**Comment by MarvinJWendt** [comment]
Hi @umutphp, thank you very much for the compliment 😄 
Nice to see that the guidelines are already understandable. But I would like to make it a bit more detailed and add test templates for all printers :)

**Comment by MarvinJWendt** [comment]
Handled in #298
