### ISSUE TITLE
Stopped spinner over writes the progressbar

### ISSUE THREAD

**Issue by wunderbarb** [pterm/pterm#555]
When running the following code, the spinner continues to run and `overwrites` the progress bar.  I would have expected to see the spinner stopped with success, and the progress bar running beneath till completion.

I am using pterm v0.12.63 with go 1.21.rc3 with Ubuntu20.04 under WSL2.

```golang
func main() {
	var spinner pterm.SpinnerPrinter
		spinner = pterm.DefaultSpinner
		spinner.Text = "Preparing transfer"
		spinner.Start()

		time.Sleep(5 * time.Second)
		spinner.Success("Everything ready")
		pterm.Println("")
		p, _ := pterm.DefaultProgressbar.WithTotal(100).WithTitle("Downloading...").Start()
		for i := 0; i < 100; i++ {
			p.Increment()
			time.Sleep(100 * time.Millisecond)
		}
	}
```

**Comment by MarvinJWendt** [comment]
Very interesting...
I'll take a look.

**Comment by MarvinJWendt** [comment]
Ah, I see. You  are using the default spinner for everything. You should bind `spinner.Start` to a new variable, as it's a fork.

I corrected your example:

```go
func main() {
	spinner, _ := pterm.DefaultSpinner.Start("Preparing transfer")

	time.Sleep(5 * time.Second)
	spinner.Success("Everything ready")
	pterm.Println("")
	p, _ := pterm.DefaultProgressbar.WithTotal(100).WithTitle("Downloading...").Start()
	for i := 0; i < 100; i++ {
		p.Increment()
		time.Sleep(100 * time.Millisecond)
	}
}
```

**Comment by wunderbarb** [comment]
Thanks Martin.  Of course, now it works.   I did not get the fact that it was `Start` that forked the instance.
May I suggest that the documentation should (could) be more explicit on that point.   Start is not only starting the spinner.  I guess it is true for every live printer.

**Comment by MarvinJWendt** [comment]
Yes, the docs could definitely be improved.

I recommend checking out the examples for the printers, they are well explained most of the time: https://github.com/pterm/pterm/blob/master/_examples/spinner/demo/main.go
