### ISSUE TITLE
Versions > `v0.12.59`: `DefaultInteractiveSelect` doesn't allow for exiting while in the middle of a selection

### ISSUE THREAD

**Issue by emmahsax** [pterm/pterm#591]
On pterm version `v0.12.66` and higher, using `CTRL-C` while in a selection using `DefaultInteractiveSelect` doesn't exit the program.

Code snippet below:

```go
package main

import (
	"fmt"

	"github.com/pterm/pterm"
)


func main() {
	list := []string{"hello", "world", "example"}

	selectedItem, _ := pterm.DefaultInteractiveSelect.
		WithDefaultText("Select an item").
		WithMaxHeight(20).
		WithOptions(list).
		Show()

	fmt.Println("selected item:", selectedItem)
}

```

When using `v0.12.59` or lower, this is the response (**and this is what I'd expect**):
```
$ go run main.go
Select an item [type to search]: 
> hello
  world
  example
exit status 1
```

When using `v0.12.66` or higher (the versions that don't error*), this is the response:
```
$ go run main.go
Select an item [type to search]: 
> hello
  world
  example
selected item: hello
```

---

*Versions `v0.12.60`-`v0.12.65` seem to error with the following message:
```
# github.com/pterm/pterm
../../../.asdf/installs/golang/1.21.0/packages/pkg/mod/github.com/pterm/pterm@v0.12.61/progressbar_printer.go:275:48: cannot use func() {…} (value of type func()) as func() bool value in argument to schedule.Every
```

**Comment by MarvinJWendt** [comment]
Thanks for reporting the issue! I'll take a look.

**Comment by panbanda** [comment]
@emmahsax It's because the new versions require you use `WithOnInterruptFunc` to handle graceful sigterms

https://github.com/pterm/pterm/pull/507

```
	selectedPod, err := pterm.DefaultInteractiveSelect.
		WithDefaultText("Select a pod").
		WithOptions([]string{"test", "what"}).
		WithOnInterruptFunc(func() {
			os.Exit(1)
		}).
		Show()
```

@MarvinJWendt should that be the default as to not break previous implementations?

**Comment by emmahsax** [comment]
That was it. Thanks! Seems like more of a breaking change as it is, but... 🤷🏼‍♀️

**Comment by MarvinJWendt** [comment]
> should that be the default as to not break previous implementations?

Yep, I think by default it should exit the program. Do you want to make an issue for that, or should I?

@emmahsax sorry for the inconvenience, I think I overlooked this change, even tho it was mentioned in the PR .-.

**Comment by panbanda** [comment]
Created one with details from Emma.

https://github.com/pterm/pterm/issues/592
