### ISSUE TITLE
PanelPrinter.Render always goes to stdout

### ISSUE THREAD

**Issue by rafaelespinoza** [pterm/pterm#613]
I noticed that for type `PanelPrinter`, its `Render` method always writes to standard output, and never to the `.Writer` field. All of the other `Render` for printer types write to the `.Writer`. 

Is there any good reason for this? Can we change it so that its behavior is consistent with the `Render` methods for other printer types? Thanks

**Comment by MarvinJWendt** [comment]
Fixed in #614, will be released in the next couple minutes.
Thanks for reporting it!
