### ISSUE TITLE
Change LineCharacter to BarCharacter

### ISSUE THREAD

**Issue by MarvinJWendt** [pterm/pterm#62]
Also make sure that tests and examples are updated.

**Comment by Owen000** [comment]
Can you assign me? Also I would like a little more info on where it is happening.

**Comment by MarvinJWendt** [comment]
Hi @Owen000, it's about this:

https://github.com/pterm/pterm/blob/4e78cfa971a30c901f3e9557a663b984b52f7f21/progressbar.go#L21

Please make sure that you refactor it everywhere it's used atm 😄
