### ISSUE TITLE
Update `Spinner` to support reseting timer

### ISSUE THREAD

**Issue by AlphaNecron** [pterm/pterm#641]
For the time being, there's literally no way to reset the timer as the underlying timestamp is entirely inaccessible and the only way to reset it is to create a new instance of Spinner. Better add a function which updates `spinner.startedAt` to `time.Now()` or publicly export `startAt` property so that users could manually alter `spinner.StartAt` according to their preferences.

**Comment by MarvinJWendt** [comment]
I could imagine the following methods:

- `.ResetTimer()` - resets the underlying timer
- `.SetStartedAt(time)` - ability to directly modify the timestamp

And for the Options:

- `WithStartedAt(time)` - to create a spinner with a custom timestamp

**Comment by MarvinJWendt** [comment]
If you're talking about directly modifying the `StartedAt` variable: While possible, this will not update the underlying `Area`. Using `.SetStartedAt(time)` will trigger an update and render the new time.

**Comment by AlphaNecron** [comment]
Oh I see, `ResetTimer` should be fine for most cases in my opinion, `SetStartedAt` seems to be redundant though.
