### ISSUE TITLE
Add `DisableOutput()` and `EnableOutput()`

### ISSUE THREAD

**Issue by MarvinJWendt** [pterm/pterm#82]
Add `DisableOutput()` and `EnableOutput()`. Those functions should set `DisableOutput` accordingly.
Also, tests should be added, to check if disabled output does not print anything.
Note: There are methods in `./internal/test_utils.go` which can check the output of code.

**Comment by anusha5695** [comment]
hi @MarvinJWendt , could you assign this to me?

**Comment by MarvinJWendt** [comment]
Hi @anusha5695, yes I will :)
Could you please make a draft PR as soon as you have your fork ready?
In that way we can discuss how the tests should look 😄

**Comment by MarvinJWendt** [comment]
Closed in #108
