### ISSUE TITLE
Add features to readme

### ISSUE THREAD

**Issue by MarvinJWendt** [pterm/pterm#83]
Add a list of features to readme. List items should be linked to an example in the readme.

**Comment by AjiArya** [comment]
Hello Marvin, I'd like to work on this.

**Comment by MarvinJWendt** [comment]
Hi @AjiArya you can put it right under the header 😄 
![image](https://user-images.githubusercontent.com/31022056/97205132-522bfa80-17b7-11eb-8675-459a0a4fc4ec.png)
